- name: Deploy snakegame App on worker1
  hosts: worker1
  become: yes
  tasks:
    - name: Stop old container
      command: docker rm -f library
      ignore_errors: yes

    - name: Pull latest image
      command: docker pull harsha497/library:latest

    - name: Run new container
      command: >
        docker run -d --name snakegame
        -p 8081:80
       harsha497/library:latest
